Transform: AWS::Serverless-2016-10-31
Parameters:
  BucketName:
    Type: String
    Default: cloud-guru-api-gateway
    Description: The name of the S3 bucket to use in api gateway
Resources:
  RestApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: SmartS3ApiGateway
  BucketResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiGateway
      ParentId: !GetAtt RestApiGateway.RootResourceId
      PathPart: !Ref BucketName
  ItemResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref BucketResource
      PathPart: "{item}"
      RestApiId: !Ref RestApiGateway
  GetItem:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiGateway
      ResourceId: !Ref ItemResource
      HttpMethod: GET
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.item: true
      MethodResponses:
        - StatusCode: 200
      Integration:
        Type: AWS
        Credentials: arn:aws:iam::287070382689:role/ApiGatewayS3Role
        IntegrationHttpMethod: GET
        IntegrationResponses:
          - StatusCode: 200
        PassthroughBehavior: WHEN_NO_MATCH
        Uri: !Sub "arn:aws:apigateway:us-east-1:s3:path/${BucketName}/{object}"
        RequestParameters:
          integration.request.path.object: "method.request.path.item"
